file_format: "1"
id: keyball_neo39
name: Keyball Neo
type: board
arch: arm
outputs:
  - usb
  - ble
url: https://github.com/tangbonze/zmk-config-Skinner39
siblings:
  - keyball_neo39_left
  - keyball_neo39_right
